### PR TITLE
Revolution, we have discovered a time machine and other questions

### PR DESCRIPTION
**Pull request by botika**
Declare `CARGO_CFG_HTMLESCAPE_DISABLE_AUTO_SIMD` environment variable before launch benchs. Now `yarte ?Send Teams` and `yarte Send Teams` takes the same. The revision of `yarte` is the one that we set. 
It is necessary to clarify that despite winning in Teams I start with a disadvantage because I escape 6 characters in front of 4, although for it the double table is the same 6 as 4 as 126, but good.

Finally what happens in the BigTable is a mystery, strange things.
Just see the series of commits `Strange things`. **I don't do anything** and it keeps running faster, it's a bit strange.

An example is TechEmpower, it would be interesting if you upload an implementation, I don't think the creator cares about having another reference.

In the movie things are equal and interesting.

### CODE REVIEW

**Comment by Kogia-sima** [comment]
@botika Thanks for your hard works and experiments.

At first, do not compile with `CARGO_CFG_HTMLESCAPE_DISABLE_AUTO_SIMD` variable. It seems that this variable will COMPLETELY disable SIMD optimization (https://github.com/botika/v_escape/blob/master/v_htmlescape/build.rs). This behaviour is completely useless in a real world server response, because there are some cases when many long strings will be rendered (e.g. chat room).

Second, the branch is too dirty. DO NOT commit dirty commits directly on the branch which will be merged. Please create another branch and paste the link to it.

Lastly, do not update unrelated dependencies. It seems `ructe` has some breaking changes from last release. This causes an compilation error for benchmarks. Please revert the update and specify the revision to the latest release.

Anyway, I'd like to appreciate your experiments and tips.

**Comment by botika** [comment]
If you remove ructe it works. 

`BigTable` **without doing anything**, just `alloc` and the `fors`. it takes the same as yours. 

Can you explain why? You may not be doing anything except alloc, ...

**Comment by Kogia-sima** [comment]
I haven't executed yet (Sorry I have another task now) but I have many thoughts about this.

I think your BigTable program certainly do something. For example, function `vo` has `&str` type in its return type, which meeds HTML escaping. HTML escaping is too complex to be inlined. Thus your BigTable benchmark has some overheads.

Also, sailfish compiler may transfom the template structure WITHOUT changing the output. This is a compile time operation, and you can see what's happened by checking the generated artifacts in `target/release/build/sailfish-compiler-***/out/templates` directory.

**Comment by botika** [comment]
https://github.com/Kogia-sima/sailfish/pull/29/commits/4f484197a808c4fc3a6f54e5df5a659aaf1b5faf#diff-1f3ebd5c3f6189ab106a083b6815497fR102-R122

Do nothing. No write. 
That is, according to your criteria, this `HTML escaping without write` costs the same to write `109915 bytes`. 
It is right? Do you want to bet something?

**Comment by Kogia-sima** [comment]
> That is, according to your criteria, this HTML escaping without write costs the same to write 109915 bytes.

No, escaping is only a one possible reason. But I believe such an operation does matter because it is called inside the inner loop. Also HTML escaping contains some loops.

**Comment by Kogia-sima** [comment]
Try creating a new benchmark which simply escapes 10000 times WITHOUT writing.

**Comment by botika** [comment]
> Try creating a new benchmark which simply escapes 10000 times WITHOUT writing.
If we build a hashing algorithm over time for each instruction, what chance is there of collisions in such a large sample?
It is ridiculous, write `109915 bytes` it costs much more than HTML escape 10000 slice of 1 or 2 characters without write. 
If I bet you something I will make the repo. 

Now I remove the html escape.

**Comment by botika** [comment]
### Results with `u8`
```bash
Big table/Sailfish      time:   [27.133 us 27.210 us 27.290 us]                                

# No write text, use u8
Big table/Yarte Send    time:   [32.151 us 32.271 us 32.406 us]   
```

**Comment by Kogia-sima** [comment]
Hmm... that's strange. Let me check after finishing the current task.

**Comment by botika** [comment]
Stranger things https://www.youtube.com/watch?v=_yuHg9Jj0qU has crazy title in Japanese. Ok, I'll wait for you. At last you understood me :smiling_face_with_three_hearts:

**Comment by Kogia-sima** [comment]
I've create a repository only for you.

https://github.com/Kogia-sima/sailfish-research

I traced the assembly carefully but could not find any issue. I've also assertion for output and `black_box` for input, but no significant difference can be detected. Maybe this problem comes from another optimization applied by sailfish-compiler?

Here is the artifact generated by sailfish-compiler.

```rust
{
    __sf_rt::render_text!(__sf_buf, "<table>\n");
    {
        __sf_rt::render_text!(__sf_buf, "<tr>");
        for row in table {
            {
                __sf_rt::render_text!(__sf_buf, "<td>");
                for col in row {
                    __sf_rt::render_escaped!(__sf_buf, *col);
                    __sf_rt::render_text!(__sf_buf, "</td><td>");
                }
                unsafe {
                    __sf_buf._set_len(__sf_buf.len() - 4usize);
                }
            }
            __sf_rt::render_text!(__sf_buf, "</tr><tr>");
        }
        unsafe {
            __sf_buf._set_len(__sf_buf.len() - 4usize);
        }
    }
    __sf_rt::render_text!(__sf_buf, "\n</table>");
}
```

**Comment by botika** [comment]
Why close? **The evidence is not clear enough.**

 `BigTable` doesn't write, the times are clear. Allocation and measuring costs exactly the same.
 
the times are very clear, it is clear that sailfish is a time machine, good luck in the future. Remove my framework from this scam.

It is shameful.
In the future, do not use my code to defraud people, much less take away my reason without a single demonstration. Do not worry that after this I will stop giving you lessons since you only see that you know what you are doing.

**Comment by Kogia-sima** [comment]
I've already confirmed that my benchmark

1. generates correct output for black-boxed inputs
2. added assertion for outputs
3. generates proper assembly

Also I've provided a full assembly output. What on earth can I do else? I've already shown these evidence. Could you provide an evidence that these evidences are not clear enough?

> BigTable doesn't write, the times are clear. Allocation and measuring costs exactly the same.

It is not true. you call `vo` function and calls `render()` method for its result. Also `Bufff::advance` and `Bufff::buf_ptr` has some implementation. You should know the compiler is not perfect. Sometimes the compiler doesn't optimize some instructions as expected.

Also sailfish transforms the template structure, so these two benchmarks are not simply comparable. You can see the generated artifacts in the target/release/build/sailfish-compiler-***/out/templates directory.

**Comment by botika** [comment]
```asm
benches::yarte_bytes::big_table::findd:
 push    rbp
 push    r15
 push    r14
 push    r13
 push    r12
 push    rbx
 mov     eax, 109960
 call    __rust_probestack
 sub     rsp, rax
 mov     rbx, rsi
 mov     qword, ptr, [rsp, +, 8], rdi
 lea     rdi, [rsp, +, 32]
 mov     edx, 109923
 xor     esi, esi
 call    qword, ptr, [rip, +, memset@GOTPCREL]
 mov     rax, qword, ptr, [rbx, +, 16]
 test    rax, rax
 je      .LBB435_6
 mov     rcx, qword, ptr, [rbx]
 lea     rax, [rax, +, 2*rax]
 lea     rax, [rcx, +, 8*rax]
 mov     qword, ptr, [rsp, +, 16], rax
 xor     ebx, ebx
 mov     r13, qword, ptr, [rip, +, _ZN7benches11yarte_bytes2vo17h55a8d24669731735E@GOTPCREL]
 mov     rbp, qword, ptr, [rip, +, _ZN13yarte_helpers7helpers8integers8write_u817haf1c4c5c43f716f2E@GOTPCREL]
 jmp     .LBB435_3
.LBB435_2:
 mov     rcx, qword, ptr, [rsp, +, 24]
 cmp     rcx, qword, ptr, [rsp, +, 16]
 je      .LBB435_6
.LBB435_3:
 mov     rax, rcx
 add     rcx, 24
 mov     r14, qword, ptr, [rax, +, 16]
 test    r14, r14
 mov     qword, ptr, [rsp, +, 24], rcx
 je      .LBB435_2
 mov     r15, qword, ptr, [rax]
 shl     r14, 3
 xor     r12d, r12d
.LBB435_5:
 mov     rdi, qword, ptr, [r15, +, r12]
 call    r13
 lea     rsi, [rsp, +, rbx]
 add     rsi, 40
 movzx   edi, al
 call    rbp
 mov     rbx, rax
 add     rbx, qword, ptr, [rsp, +, 32]
 mov     qword, ptr, [rsp, +, 32], rbx
 add     r12, 8
 cmp     r14, r12
 jne     .LBB435_5
 jmp     .LBB435_2
.LBB435_6:
 mov     rax, qword, ptr, [rsp, +, 8]
 mov     qword, ptr, [rax], 1
 xorps   xmm0, xmm0
 movups  xmmword, ptr, [rax, +, 8], xmm0
 add     rsp, 109960
 pop     rbx
 pop     r12
 pop     r13
 pop     r14
 pop     r15
 pop     rbp
 ret
```
Go through a debugger.

**Comment by botika** [comment]
With Vec<u8>, no Write, with same results:
```asm
benches::yarte_bytes::big_table::findd:
 push    rbp
 push    r15
 push    r14
 push    r13
 push    r12
 push    rbx
 sub     rsp, 56
 mov     r15, rsi
 mov     qword, ptr, [rsp, +, 32], rdi
 mov     ebp, 109915
 mov     edi, 109915
 mov     esi, 1
 call    qword, ptr, [rip, +, __rust_alloc@GOTPCREL]
 test    rax, rax
 je      .LBB435_1
 mov     rbx, rax
 mov     qword, ptr, [rsp, +, 8], rax
 movq    xmm0, rbp
 movdqu  xmmword, ptr, [rsp, +, 16], xmm0
 mov     rax, qword, ptr, [r15, +, 16]
 test    rax, rax
 je      .LBB435_11
 mov     rcx, qword, ptr, [r15]
 lea     rax, [rax, +, 2*rax]
 lea     rax, [rcx, +, 8*rax]
 mov     qword, ptr, [rsp, +, 40], rax
 xor     r14d, r14d
 mov     rbp, qword, ptr, [rip, +, _ZN13yarte_helpers7helpers8integers8write_u817haf1c4c5c43f716f2E@GOTPCREL]
 jmp     .LBB435_6
.LBB435_7:
 mov     rax, r14
.LBB435_5:
 mov     rcx, qword, ptr, [rsp, +, 48]
 add     rcx, 24
 mov     r14, rax
 cmp     rcx, qword, ptr, [rsp, +, 40]
 je      .LBB435_11
.LBB435_6:
 mov     r12, qword, ptr, [rcx, +, 16]
 test    r12, r12
 mov     qword, ptr, [rsp, +, 48], rcx
 je      .LBB435_7
 mov     r15, qword, ptr, [rcx]
 shl     r12, 3
 xor     r13d, r13d
.LBB435_9:
 mov     rdi, qword, ptr, [r15, +, r13]
 call    qword, ptr, [rip, +, _ZN7benches11yarte_bytes2vo17h55a8d24669731735E@GOTPCREL]
 lea     rsi, [rbx, +, r14]
 movzx   edi, al
 call    rbp
 add     rax, r14
 mov     qword, ptr, [rsp, +, 24], rax
 add     r13, 8
 mov     r14, rax
 cmp     r12, r13
 jne     .LBB435_9
 jmp     .LBB435_5
.LBB435_11:
 mov     rax, qword, ptr, [rsp, +, 24]
 mov     rcx, qword, ptr, [rsp, +, 32]
 mov     qword, ptr, [rcx, +, 16], rax
 mov     rax, qword, ptr, [rsp, +, 8]
 mov     qword, ptr, [rcx], rax
 mov     rax, qword, ptr, [rsp, +, 16]
 mov     qword, ptr, [rcx, +, 8], rax
 add     rsp, 56
 pop     rbx
 pop     r12
 pop     r13
 pop     r14
 pop     r15
 pop     rbp
 ret
.LBB435_1:
 mov     edi, 109915
 mov     esi, 1
 call    qword, ptr, [rip, +, _ZN5alloc5alloc18handle_alloc_error17h7f6a7a00afe6ad92E@GOTPCREL]
 ud2
.LBB435_2:
 mov     rbx, rax
 lea     rdi, [rsp, +, 8]
 call    core::ptr::drop_in_place
 mov     rdi, rbx
 call    _Unwind_Resume
 ud2
```

**Comment by Kogia-sima** [comment]
I advise you that, from my experience, function call via general purpose register is slower than via the base pointer (https://github.com/Kogia-sima/sailfish/issues/24).

Also it seems you call `yarte-helper::helper::integers::write_u8` function. I've generated the assembly for this.

```nasm
yarte_integer::write_u8:
 push    rax
 cmp     dil, 10
 jae     .LBB4_1
 add     dil, 48
 mov     byte, ptr, [rsi], dil
 mov     eax, 1
 pop     rcx
 ret
.LBB4_1:
 cmp     dil, 100
 jae     .LBB4_2
 add     dil, dil
 movzx   eax, dil
 cmp     al, -57
 ja      .LBB4_8
 lea     rcx, [rip, +, .Lanon.01512aba9fc4bb3ec06e609b0b1be792.0]
 mov     dl, byte, ptr, [rax, +, rcx]
 mov     byte, ptr, [rsi], dl
 or      rax, 1
 cmp     rax, 199
 ja      .LBB4_10
 mov     al, byte, ptr, [rax, +, rcx]
 mov     byte, ptr, [rsi, +, 1], al
 mov     eax, 2
 pop     rcx
 ret
.LBB4_2:
 movzx   eax, dil
 lea     ecx, [rax, +, 4*rax]
 lea     eax, [rax, +, 8*rcx]
 shr     eax, 12
 imul    ecx, eax, 100
 sub     dil, cl
 movzx   edx, dil
 or      al, 48
 mov     byte, ptr, [rsi], al
 lea     rcx, [rip, +, .Lanon.01512aba9fc4bb3ec06e609b0b1be792.0]
 mov     al, byte, ptr, [rcx, +, 2*rdx]
 mov     byte, ptr, [rsi, +, 1], al
 lea     rax, [rdx, +, rdx]
 add     rax, 1
 cmp     rax, 200
 jae     .LBB4_11
 mov     al, byte, ptr, [rax, +, rcx]
 mov     byte, ptr, [rsi, +, 2], al
 mov     eax, 3
 pop     rcx
 ret
.LBB4_8:
 lea     rdi, [rip, +, .Lanon.01512aba9fc4bb3ec06e609b0b1be792.21]
 mov     edx, 200
 mov     rsi, rax
 call    qword, ptr, [rip, +, _ZN4core9panicking18panic_bounds_check17h9bed4acc8b167212E@GOTPCREL]
 ud2
.LBB4_10:
 lea     rdi, [rip, +, .Lanon.01512aba9fc4bb3ec06e609b0b1be792.22]
 mov     edx, 200
 mov     rsi, rax
 call    qword, ptr, [rip, +, _ZN4core9panicking18panic_bounds_check17h9bed4acc8b167212E@GOTPCREL]
 ud2
.LBB4_11:
 lea     rdi, [rip, +, .Lanon.01512aba9fc4bb3ec06e609b0b1be792.23]
 mov     edx, 200
 mov     rsi, rax
 call    qword, ptr, [rip, +, _ZN4core9panicking18panic_bounds_check17h9bed4acc8b167212E@GOTPCREL]
 ud2
```

I can see some array-boundary checks in this function. I don't know much about the yarte internal behaviour, but I think these operations can be skipped.

**Comment by botika** [comment]
If you no open no actualize commits. I add your changes with same results.

**Comment by Kogia-sima** [comment]
```diff
--- a/benches/src/yarte_bytes.rs
+++ b/benches/src/yarte_bytes.rs
@@ -136,7 +136,24 @@ pub fn big_table(b: &mut criterion::Bencher<'_>, size: &usize) {

     #[inline(never)]
     fn findd(t: &BigTable) -> Vec<u8> {
-        t.call::<Buff>(109915)
+        use yarte_helpers::helpers::integers::Integer;
+
+        let mut buf = Buff::with_capacity(109915);
+        buf.extend_from_slice(b"<table>");
+        for row in &t.table {
+            buf.extend_from_slice(b"<tr>");
+            for col in row {
+                buf.extend_from_slice(b"<td>");
+                unsafe {
+                    Integer::write_to(*col as u8, buf.buf_ptr());
+                }
+                buf.extend_from_slice(b"</td>");
+            }
+            buf.extend_from_slice(b"</tr>");
+        }
+        buf.extend_from_slice(b"</table>");
+        buf.freeze()
     }
     let t = BigTable { table };
     b.iter(|| findd(&t));
```

Result:

```console
Big table/Sailfish      time:   [60.892 us 60.982 us 61.088 us]
Big table/Yarte Send    time:   [44.169 us 44.215 us 44.270 us]
```

This result suggests that the problem is caused by yarte implementation, rather than sailfish implementation.

Do not bother us if you don't have concrete evidence. Our team has already working on the development of MySQL API, In-memory session, debugger, and profiler.

**Comment by botika** [comment]
It is not a matter of the interns of yarte. 
You have a copy of the generated code and it works at the same speed as yours. It is the fault of the `Derive`, although it is very strange, more strange things.
What I do not understand is why you have closed this PR, is it an important issue and must we get to the end of the matter?
```rust
    #[inline(never)]
    fn findd(t: &BigTable) -> Vec<u8> {
        use yarte::*;

        let mut buf = Buff::with_capacity(109915);
        buf.extend_from_slice(b"<table>");
        for row in (&t.table).__into_citer() {
            buf.extend_from_slice(b"<tr>");
            for col in (&row).__into_citer() {
                buf.extend_from_slice(b"<td>");
                col.__render_itb(&mut buf);
                buf.extend_from_slice(b"</td>");
            }
            buf.extend_from_slice(b"</tr>");
        }
        buf.extend_from_slice(b"</table>");
        buf.freeze()
    }
```

```bash
Big table/Sailfish      time:   [30.208 us 30.258 us 30.317 us]                                
# Writing normal
Big table/Yarte Send    time:   [30.312 us 30.354 us 30.396 us]   
```

**Comment by Kogia-sima** [comment]
You program contains Infinite loop.

https://github.com/botika/sailfish/blob/58b6daf259d8f8c154b57dfcf79587f6e711f747/benches/src/yarte_bytes.rs#L47

> What I do not understand is why you have closed this PR, is it an important issue and must we get to the end of the matter?

How much it matters has nothing to do with the reason of close. I close this PR because the problem is apparently caused by Yarte. Any problem is not found in sailfish. It is no use disposing this issue for another people who visited this repository.

**Comment by Kogia-sima** [comment]
If you want to solve the problem you should recreate the issue on your repository, and do not bother us. We are already on the next stage and can't take so much time for the template engine, which is just a small component of the web application.

**Comment by botika** [comment]
Good luck. His attempt to reinvent the wheel seems perfect to me, but if a principle had not put `yarte` as a reference of evil you would not have not know if I exist.

I wait for you at Techempower.

**Pull request closed without merging**
